### ISSUE TITLE
sequence plot command fails if there is only land

### ISSUE THREAD

**Issue by mcflugen** [sequence-dev/sequence#40]
* sequence version: 0.4.1.dev0
* Python version: 3.10
* Operating System: osx

### Description

If I run a *Sequence* simulation that generates a profile that is all above sea level, the `sequence plot` command fails with the following error,
```python
Traceback (most recent call last):
...
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### What I Did

Run the *Sequence* on the default bathymetry but only extend the modeled profile out to 10 km. That is, the `sequence.grid` section of *sequence.toml* looks like,
```toml
[sequence.grid]
shape = [3, 100]
xy_spacing = 100.0
xy_of_lower_left = [0.0, 0.0]
```
